name: Tag releases with minor and major version

on:
  release:
    types: [released]

permissions: {}

jobs:
  tag-v1:
    name: Tag v1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Update tag
        run: |
          major_tag="$(python .github/scripts/get_version.py "${GITHUB_REF}" major)"
          minor_tag="$(python .github/scripts/get_version.py "${GITHUB_REF}" minor)"
          git tag $major_tag
          git tag $minor_tag
          git push origin HEAD:refs/heads/master --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
